// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacter() {
  return window['go']['main']['App']['AddCharacter']();
}

export function CountTokens(arg1) {
  return window['go']['main']['App']['CountTokens'](arg1);
}

export function CrawlPage(arg1, arg2) {
  return window['go']['main']['App']['CrawlPage'](arg1, arg2);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteComfyWorkflow(arg1) {
  return window['go']['main']['App']['DeleteComfyWorkflow'](arg1);
}

export function ExportCharacter(arg1, arg2) {
  return window['go']['main']['App']['ExportCharacter'](arg1, arg2);
}

export function ExportCharacterPNG(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportCharacterPNG'](arg1, arg2, arg3, arg4);
}

export function ExportCharactersBulk(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportCharactersBulk'](arg1, arg2, arg3, arg4);
}

export function ExportLorebook(arg1) {
  return window['go']['main']['App']['ExportLorebook'](arg1);
}

export function GenerateCharacterBulk(arg1) {
  return window['go']['main']['App']['GenerateCharacterBulk'](arg1);
}

export function GenerateField(arg1, arg2) {
  return window['go']['main']['App']['GenerateField'](arg1, arg2);
}

export function GenerateImagePrompt(arg1, arg2) {
  return window['go']['main']['App']['GenerateImagePrompt'](arg1, arg2);
}

export function GeneratePortrait(arg1) {
  return window['go']['main']['App']['GeneratePortrait'](arg1);
}

export function GenerateProjectImage(arg1) {
  return window['go']['main']['App']['GenerateProjectImage'](arg1);
}

export function GetActiveCharacter() {
  return window['go']['main']['App']['GetActiveCharacter']();
}

export function GetCachedCrawl() {
  return window['go']['main']['App']['GetCachedCrawl']();
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetComfyCheckpoints() {
  return window['go']['main']['App']['GetComfyCheckpoints']();
}

export function GetComfyConfig() {
  return window['go']['main']['App']['GetComfyConfig']();
}

export function GetComfyLoRAs() {
  return window['go']['main']['App']['GetComfyLoRAs']();
}

export function GetComfySamplers() {
  return window['go']['main']['App']['GetComfySamplers']();
}

export function GetComfySchedulers() {
  return window['go']['main']['App']['GetComfySchedulers']();
}

export function GetComfyVAEs() {
  return window['go']['main']['App']['GetComfyVAEs']();
}

export function GetComfyWorkflowByName(arg1) {
  return window['go']['main']['App']['GetComfyWorkflowByName'](arg1);
}

export function GetComfyWorkflowTemplate(arg1) {
  return window['go']['main']['App']['GetComfyWorkflowTemplate'](arg1);
}

export function GetComfyWorkflows() {
  return window['go']['main']['App']['GetComfyWorkflows']();
}

export function GetDefaultPromptTemplates() {
  return window['go']['main']['App']['GetDefaultPromptTemplates']();
}

export function GetLorebook() {
  return window['go']['main']['App']['GetLorebook']();
}

export function GetPortrait(arg1) {
  return window['go']['main']['App']['GetPortrait'](arg1);
}

export function GetProjectFieldEndpoints() {
  return window['go']['main']['App']['GetProjectFieldEndpoints']();
}

export function GetProjectImage() {
  return window['go']['main']['App']['GetProjectImage']();
}

export function GetProjectThumbnail(arg1) {
  return window['go']['main']['App']['GetProjectThumbnail'](arg1);
}

export function GetPromptTemplates() {
  return window['go']['main']['App']['GetPromptTemplates']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportComfyWorkflow(arg1) {
  return window['go']['main']['App']['ImportComfyWorkflow'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function NewProject() {
  return window['go']['main']['App']['NewProject']();
}

export function OpenProjectBundle(arg1) {
  return window['go']['main']['App']['OpenProjectBundle'](arg1);
}

export function ParseComfyWorkflowParams(arg1) {
  return window['go']['main']['App']['ParseComfyWorkflowParams'](arg1);
}

export function PickExportFolder() {
  return window['go']['main']['App']['PickExportFolder']();
}

export function PickOpenBundle() {
  return window['go']['main']['App']['PickOpenBundle']();
}

export function PickSaveBundle() {
  return window['go']['main']['App']['PickSaveBundle']();
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function RemoveProject(arg1, arg2) {
  return window['go']['main']['App']['RemoveProject'](arg1, arg2);
}

export function SaveComfyWorkflowTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveComfyWorkflowTemplate'](arg1, arg2);
}

export function SaveLorebook(arg1) {
  return window['go']['main']['App']['SaveLorebook'](arg1);
}

export function SavePortrait(arg1, arg2) {
  return window['go']['main']['App']['SavePortrait'](arg1, arg2);
}

export function SaveProjectBundle(arg1) {
  return window['go']['main']['App']['SaveProjectBundle'](arg1);
}

export function SaveProjectImage(arg1) {
  return window['go']['main']['App']['SaveProjectImage'](arg1);
}

export function SavePromptTemplates(arg1) {
  return window['go']['main']['App']['SavePromptTemplates'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendCrawlToProject(arg1) {
  return window['go']['main']['App']['SendCrawlToProject'](arg1);
}

export function SetActiveCharacter(arg1) {
  return window['go']['main']['App']['SetActiveCharacter'](arg1);
}

export function SetProjectFieldEndpoint(arg1, arg2) {
  return window['go']['main']['App']['SetProjectFieldEndpoint'](arg1, arg2);
}

export function SetProjectStatus(arg1, arg2) {
  return window['go']['main']['App']['SetProjectStatus'](arg1, arg2);
}

export function TestComfyUIEndpoint(arg1, arg2) {
  return window['go']['main']['App']['TestComfyUIEndpoint'](arg1, arg2);
}

export function TestLLMEndpoint(arg1) {
  return window['go']['main']['App']['TestLLMEndpoint'](arg1);
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}
