// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {crawler} from '../models';
import {settings} from '../models';
import {llm} from '../models';

export function CrawlPage(arg1:string,arg2:crawler.CrawlOptions):Promise<crawler.CrawlResult>;

export function GetCachedCrawl():Promise<crawler.CrawlResult>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function TestLLMEndpoint(arg1:settings.LLMEndpoint):Promise<llm.TestResult>;
