// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacter() {
  return window['go']['main']['App']['AddCharacter']();
}

export function CountTokens(arg1) {
  return window['go']['main']['App']['CountTokens'](arg1);
}

export function CrawlPage(arg1, arg2) {
  return window['go']['main']['App']['CrawlPage'](arg1, arg2);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function ExportCharacter(arg1, arg2) {
  return window['go']['main']['App']['ExportCharacter'](arg1, arg2);
}

export function ExportLorebook(arg1) {
  return window['go']['main']['App']['ExportLorebook'](arg1);
}

export function GenerateCharacterBulk(arg1) {
  return window['go']['main']['App']['GenerateCharacterBulk'](arg1);
}

export function GenerateField(arg1, arg2) {
  return window['go']['main']['App']['GenerateField'](arg1, arg2);
}

export function GetActiveCharacter() {
  return window['go']['main']['App']['GetActiveCharacter']();
}

export function GetCachedCrawl() {
  return window['go']['main']['App']['GetCachedCrawl']();
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetLorebook() {
  return window['go']['main']['App']['GetLorebook']();
}

export function GetPromptTemplates() {
  return window['go']['main']['App']['GetPromptTemplates']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenProjectBundle(arg1) {
  return window['go']['main']['App']['OpenProjectBundle'](arg1);
}

export function PickExportFolder() {
  return window['go']['main']['App']['PickExportFolder']();
}

export function PickOpenBundle() {
  return window['go']['main']['App']['PickOpenBundle']();
}

export function PickSaveBundle() {
  return window['go']['main']['App']['PickSaveBundle']();
}

export function SaveLorebook(arg1) {
  return window['go']['main']['App']['SaveLorebook'](arg1);
}

export function SaveProjectBundle(arg1) {
  return window['go']['main']['App']['SaveProjectBundle'](arg1);
}

export function SavePromptTemplates(arg1) {
  return window['go']['main']['App']['SavePromptTemplates'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActiveCharacter(arg1) {
  return window['go']['main']['App']['SetActiveCharacter'](arg1);
}

export function TestLLMEndpoint(arg1) {
  return window['go']['main']['App']['TestLLMEndpoint'](arg1);
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}
