// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compose} from '../models';
import {crawler} from '../models';
import {prompts} from '../models';
import {settings} from '../models';
import {project} from '../models';
import {llm} from '../models';

export function AddCharacter():Promise<compose.Character>;

export function CountTokens(arg1:string):Promise<number>;

export function CrawlPage(arg1:string,arg2:crawler.CrawlOptions):Promise<crawler.CrawlResult>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function ExportCharacter(arg1:number,arg2:string):Promise<string>;

export function GenerateCharacterBulk(arg1:Array<string>):Promise<compose.Character>;

export function GenerateField(arg1:string,arg2:string):Promise<compose.Character>;

export function GetActiveCharacter():Promise<compose.Character>;

export function GetCachedCrawl():Promise<crawler.CrawlResult>;

export function GetCharacters():Promise<Array<compose.Character>>;

export function GetPromptTemplates():Promise<prompts.TemplateSet>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function OpenProjectBundle(arg1:string):Promise<project.ProjectManifest>;

export function PickExportFolder():Promise<string>;

export function PickOpenBundle():Promise<string>;

export function PickSaveBundle():Promise<string>;

export function SaveProjectBundle(arg1:string):Promise<void>;

export function SavePromptTemplates(arg1:prompts.TemplateSet):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetActiveCharacter(arg1:number):Promise<void>;

export function TestLLMEndpoint(arg1:settings.LLMEndpoint):Promise<llm.TestResult>;

export function UpdateCharacter(arg1:compose.Character):Promise<void>;
