// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compose} from '../models';
import {crawler} from '../models';
import {comfy} from '../models';
import {settings} from '../models';
import {prompts} from '../models';
import {lorebook} from '../models';
import {project} from '../models';
import {llm} from '../models';

export function AddCharacter():Promise<compose.Character>;

export function CountTokens(arg1:string):Promise<number>;

export function CrawlPage(arg1:string,arg2:crawler.CrawlOptions):Promise<crawler.CrawlResult>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteComfyWorkflow(arg1:string):Promise<void>;

export function ExportCharacter(arg1:number,arg2:string):Promise<string>;

export function ExportLorebook(arg1:string):Promise<string>;

export function GenerateCharacterBulk(arg1:Array<string>):Promise<compose.Character>;

export function GenerateField(arg1:string,arg2:string):Promise<compose.Character>;

export function GenerateImagePrompt(arg1:number,arg2:string):Promise<string>;

export function GeneratePortrait(arg1:comfy.GenerationParams):Promise<Array<comfy.CompletedImage>>;

export function GenerateProjectImage(arg1:comfy.GenerationParams):Promise<Array<comfy.CompletedImage>>;

export function GetActiveCharacter():Promise<compose.Character>;

export function GetCachedCrawl():Promise<crawler.CrawlResult>;

export function GetCharacters():Promise<Array<compose.Character>>;

export function GetComfyCheckpoints():Promise<Array<string>>;

export function GetComfyConfig():Promise<settings.ComfyConfig>;

export function GetComfyLoRAs():Promise<Array<string>>;

export function GetComfySamplers():Promise<Array<string>>;

export function GetComfySchedulers():Promise<Array<string>>;

export function GetComfyVAEs():Promise<Array<string>>;

export function GetComfyWorkflowByName(arg1:string):Promise<comfy.ComfyWorkflow>;

export function GetComfyWorkflowTemplate(arg1:string):Promise<string>;

export function GetComfyWorkflows():Promise<Array<comfy.ComfyWorkflow>>;

export function GetDefaultPromptTemplates():Promise<prompts.TemplateSet>;

export function GetLorebook():Promise<Array<lorebook.Entry>>;

export function GetPortrait(arg1:number):Promise<Array<number>>;

export function GetProjectImage():Promise<Array<number>>;

export function GetPromptTemplates():Promise<prompts.TemplateSet>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function ImportComfyWorkflow(arg1:string):Promise<comfy.ComfyWorkflow>;

export function OpenProjectBundle(arg1:string):Promise<project.ProjectManifest>;

export function ParseComfyWorkflowParams(arg1:string):Promise<comfy.WorkflowParams>;

export function PickExportFolder():Promise<string>;

export function PickOpenBundle():Promise<string>;

export function PickSaveBundle():Promise<string>;

export function SaveComfyWorkflowTemplate(arg1:string,arg2:string):Promise<void>;

export function SaveLorebook(arg1:Array<lorebook.Entry>):Promise<void>;

export function SavePortrait(arg1:number,arg2:Array<number>):Promise<void>;

export function SaveProjectBundle(arg1:string):Promise<void>;

export function SaveProjectImage(arg1:Array<number>):Promise<void>;

export function SavePromptTemplates(arg1:prompts.TemplateSet):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SetActiveCharacter(arg1:number):Promise<void>;

export function TestComfyUIEndpoint(arg1:string,arg2:string):Promise<llm.TestResult>;

export function TestLLMEndpoint(arg1:settings.LLMEndpoint):Promise<llm.TestResult>;

export function UpdateCharacter(arg1:compose.Character):Promise<void>;
