// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlPage(arg1, arg2) {
  return window['go']['main']['App']['CrawlPage'](arg1, arg2);
}

export function GetCachedCrawl() {
  return window['go']['main']['App']['GetCachedCrawl']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestLLMEndpoint(arg1) {
  return window['go']['main']['App']['TestLLMEndpoint'](arg1);
}
